// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartAccessLift.Web.Data;

#nullable disable

namespace SmartAccessLift.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartAccessLift.Web.Models.Entities.AccessLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("FloorId")
                        .HasColumnType("int");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("VisitorAccessId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.HasIndex("Outcome");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("VisitorAccessId");

                    b.HasIndex("FloorId", "Timestamp");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("AccessLogs", t =>
                        {
                            t.HasCheckConstraint("CK_AccessLog_AccessMethod", "[AccessMethod] IN ('NFC', 'Fingerprint', 'QR', 'AdminOverride')");

                            t.HasCheckConstraint("CK_AccessLog_Outcome", "[Outcome] IN ('Successful', 'Denied')");

                            t.HasCheckConstraint("CK_AccessLog_UserOrVisitor", "([UserId] IS NOT NULL) OR ([VisitorAccessId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("SmartAccessLift.Web.Models.Entities.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FloorNumber")
                        .IsUnique();

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("SmartAccessLift.Web.Models.Entities.FloorPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FloorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GrantedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.HasIndex("GrantedBy");

                    b.HasIndex("IsAllowed");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "FloorId")
                        .IsUnique();

                    b.ToTable("FloorPermissions");
                });

            modelBuilder.Entity("SmartAccessLift.Web.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_User_Role", "[Role] IN ('Resident', 'Admin')");
                        });
                });

            modelBuilder.Entity("SmartAccessLift.Web.Models.Entities.VisitorAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FirstUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("QRCodeImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UseCount")
                        .HasColumnType("int");

                    b.Property<string>("VisitorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("QRCode")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("StartTime", "EndTime");

                    b.ToTable("VisitorAccesses", t =>
                        {
                            t.HasCheckConstraint("CK_VisitorAccess_EndAfterStart", "[EndTime] > [StartTime]");

                            t.HasCheckConstraint("CK_VisitorAccess_Status", "[Status] IN ('Pending', 'Active', 'Expired')");
                        });
                });

            modelBuilder.Entity("SmartAccessLift.Web.Models.Entities.VisitorAccessFloor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FloorId")
                        .HasColumnType("int");

                    b.Property<int>("VisitorAccessId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.HasIndex("VisitorAccessId");

                    b.HasIndex("VisitorAccessId", "FloorId")
                        .IsUnique();

                    b.ToTable("VisitorAccessFloors");
                });

            modelBuilder.Entity("SmartAccessLift.Web.Models.Entities.AccessLog", b =>
                {
                    b.HasOne("SmartAccessLift.Web.Models.Entities.Floor", "Floor")
                        .WithMany("AccessLogs")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartAccessLift.Web.Models.Entities.User", "User")
                        .WithMany("AccessLogs")
                        .HasForeignKey("UserId");

                    b.HasOne("SmartAccessLift.Web.Models.Entities.VisitorAccess", "VisitorAccess")
                        .WithMany("AccessLogs")
                        .HasForeignKey("VisitorAccessId");

                    b.Navigation("Floor");

                    b.Navigation("User");

                    b.Navigation("VisitorAccess");
                });

            modelBuilder.Entity("SmartAccessLift.Web.Models.Entities.FloorPermission", b =>
                {
                    b.HasOne("SmartAccessLift.Web.Models.Entities.Floor", "Floor")
                        .WithMany("FloorPermissions")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartAccessLift.Web.Models.Entities.User", "GrantedByUser")
                        .WithMany()
                        .HasForeignKey("GrantedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SmartAccessLift.Web.Models.Entities.User", "User")
                        .WithMany("FloorPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");

                    b.Navigation("GrantedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartAccessLift.Web.Models.Entities.VisitorAccess", b =>
                {
                    b.HasOne("SmartAccessLift.Web.Models.Entities.User", "CreatedByUser")
                        .WithMany("CreatedVisitorAccesses")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("SmartAccessLift.Web.Models.Entities.VisitorAccessFloor", b =>
                {
                    b.HasOne("SmartAccessLift.Web.Models.Entities.Floor", "Floor")
                        .WithMany("VisitorAccessFloors")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartAccessLift.Web.Models.Entities.VisitorAccess", "VisitorAccess")
                        .WithMany("VisitorAccessFloors")
                        .HasForeignKey("VisitorAccessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");

                    b.Navigation("VisitorAccess");
                });

            modelBuilder.Entity("SmartAccessLift.Web.Models.Entities.Floor", b =>
                {
                    b.Navigation("AccessLogs");

                    b.Navigation("FloorPermissions");

                    b.Navigation("VisitorAccessFloors");
                });

            modelBuilder.Entity("SmartAccessLift.Web.Models.Entities.User", b =>
                {
                    b.Navigation("AccessLogs");

                    b.Navigation("CreatedVisitorAccesses");

                    b.Navigation("FloorPermissions");
                });

            modelBuilder.Entity("SmartAccessLift.Web.Models.Entities.VisitorAccess", b =>
                {
                    b.Navigation("AccessLogs");

                    b.Navigation("VisitorAccessFloors");
                });
#pragma warning restore 612, 618
        }
    }
}
